### ISSUE TITLE
Debounce on RCIN for Flight Mode switch

### ISSUE THREAD

**Issue by danlaks** [SpektreWorks/ardupilot#1]

**Comment by magicrub** [comment]
This is already implemented properly (ms timer of same values) in Copter and Rover. Plane's implementation is an older simpler method (looks for two consecutive same non-zero values) but still valid. I looked into unifying it with the other vehicles but it gets very complicated with some silly geofence stuff that looks at previous states of the rc input for it to revert back to, depending on the current rc in state. All other vehicles do geofencing totally differently. I also see in the code comments that someone else has made an attempt (like me) to unify this and gave up (like me). The real solution is to unify geofenceing to there's no reliance on the stupid rc input for other system.

For now, I think the risk is very low that this will ever impact you and is handled much better than how the ICE module was handling rc inputs.

closing.
